### PR TITLE
feat: base64 image output

### PR DESCRIPTION
**Pull request by Dekita**
added changes for base64 image output when no s3 bucket is set. also added basic 'custom' directory for adding models/custom nodes for being mounted, updated doc, etc. :)

### CODE REVIEW

**Comment by TimPietrusky** [comment]
Just for reference: This is a fix for #5

**Comment by TimPietrusky** [comment]
@Dekita thanks for creating the PR.

Regarding the custom node: Do we actually need the example-node-code in here? Wouldn't it be enough to just update the docs (as you did) and maybe add the folders + .gitkeep? 

And is it also enough to just have the custom-node in the folder? I thought that also the dependencies must be download for a custom-node and this happens in ComfyUI somehow (I guess on the fly?). So when you just add the custom node into the Docker image, it would need to download dependencies in every worker when the workflow is triggered. Which would lead to longer execution times for your worker. Or am I wrong?

**Comment by Dekita** [comment]
no the example node isnt required at all. generally the custom nodes would be in a subfolder of the 'custom_nodes' directory and if needed, would have a requirements.txt file for anything that hasto be downloaded. you are correct this would be done before execution if it doesnt already exist; however, if your node lib doesnt require additional libs then no need to download anything.

**Comment by TimPietrusky** [comment]
@Dekita yeah that sounds about right. Do you mind moving the "custom nodes" code/docs out of this PR so that we can work on the integration separately and merge the base64 changes directly?

**Comment by Dekita** [comment]
yea thats fine. pushed those changes now. think i got verything regarding the custom models/nodes stuff that i added :)

**Review by TimPietrusky — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
